DROP TABLE IF EXISTS uk_analytics_jobs;

CREATE TABLE uk_analytics_jobs (
    job_id TEXT PRIMARY KEY,
    search_term TEXT,
    title TEXT,
    company TEXT,
    location TEXT,
    location_area TEXT,
    latitude NUMERIC,
    longitude NUMERIC,
    category TEXT,
    salary_min NUMERIC,
    salary_max NUMERIC,
    contract_type TEXT,
    contract_time TEXT,
    created TIMESTAMPTZ,
    extracted_at TIMESTAMPTZ,
    posting_date DATE,
    salary_mid NUMERIC,
    salary_available INTEGER,
    salary_mid_clean NUMERIC,
    role_group TEXT,
    seniority TEXT,
    region TEXT,
    skill_sql INTEGER,
    skill_python INTEGER,
    skill_r INTEGER,
    skill_power_bi INTEGER,
    skill_tableau INTEGER,
    skill_excel INTEGER,
    skill_looker INTEGER,
    skill_aws INTEGER,
    skill_azure INTEGER,
    skill_gcp INTEGER,
    skill_snowflake INTEGER,
    skill_databricks INTEGER,
    skill_spark INTEGER,
    skill_dbt INTEGER,
    skill_power_query INTEGER,
    skill_dax INTEGER,
    skill_sas INTEGER,
    skill_alteryx INTEGER,
    skill_statistics INTEGER,
    skill_machine_learning INTEGER,
    skill_git INTEGER,
    skills_count INTEGER
);
